// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlxqgywaquwujwidkzpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJseHFneXdhcXV3dWp3aWRrenBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDUzMjIsImV4cCI6MjA3MDY4MTMyMn0.mWgFLX4et2FsYfH1PhSk1fi8Pag7nCGmQS9CTvyqfP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});